version: 0.2
env:
   parameter-store:
           DB_Name: "/vaibhav/db_name"
           DB_User: "/vaibhav/db_user"
           DB_Password: "/vaibhav/db_password"
           DB_Host: "/vaibhav/db_host"
           AUTH_KEY: "/vaibhav/auth_key"
           SECURE_AUTH_KEY: "/vaibhav/secure_ak"
           LOGGED_IN_KEY: "/vaibhav/logded_ik"
           NONCE_KEY: "/vaibhav/nonce_key"
           AUTH_SALT: "/vaibhav/auth_salt"
           SECURE_AUTH_SALT: "/vaibhav/Secure_as"
           LOGGED_IN_SALT: "/vaibhav/logged_is"
           NONCE_SALT: "/vaibhav/nonce_salt"
phases:
   build:
        commands:
        - sed -i 's/database_name_here/'$DB_Name'/' wp-config.php
        - sed -i 's/username_here/'$DB_User'/' wp-config.php
        - sed -i 's/password_here/'$DB_Password'/' wp-config.php
        - sed -i 's/put your unique phrase here/'$DB_Host'/' wp-config.php
        - sed -i 's/put your unique phrase here/'$AUTH_KEY'/' wp-config.php
        - sed -i 's/put your unique phrase here/'SECURE_AUTH_KEY'/' wp-config.php
        - sed -i 's/put your unique phrase here/'LOGGED_IN_KEY'/' wp-config.php
        - sed -i 's/put your unique phrase here/'NONCE_KEY'/' wp-config.php
        - sed -i 's/put your unique phrase here/'AUTH_SALT'/' wp-config.php
        - sed -i 's/put your unique phrase here/'SECURE_AUTH_SALT'/' wp-config.php
        - sed -i 's/put your unique phrase here/'LOGGED_IN_SALT'/' wp-config.php
        - sed -i 's/put your unique phrase here/'NONCE_SALT'/' wp-config.php
artifacts:
        files:
            - '**/*'
